title: Setup Guides
nav:
  - getting_started.md
  - concepts.md
  - setup_core_crud.md
  - powerfields.md
  - poweractions.md
  - filtering.md
  - forms.md
  - inline_editing.md
  - bulk_edit_sync.md
  - async_manager.md
  - bulk_edit_async.md
  - async_dashboard.md
  - styling_tailwind.md
