title: Setup Guides
nav:
  - Getting Started: getting_started.md
  - Setup & Core CRUD basics: setup_core_crud.md
  - Filtering: filtering.md
  - Forms: forms.md
  - Inline Editing: inline_editing.md
  - Bulk Editing (Synchronous): bulk_edit_sync.md
  - Async Manager: async_manager.md
  - Bulk Editing (Async): bulk_edit_async.md
  - Async dashboard add-on: async_dashboard.md
  - Styling & Tailwind: styling_tailwind.md
  - PowerCRUD Concepts: concepts.md
