site_name: Django PowerCRUD
site_author: Michael Foulds

docs_dir: docs/mkdocs
site_dir: site

dev_addr: 0.0.0.0:10005
repo_url: https://github.com/doctor-cornelius/django-powercrud
edit_uri: blob/mkdocs/docs/

  # ------------------------------------------------------------------
watch:
  - docs/mkdocs

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.caret # caret (^) will superscript next char
  - pymdownx.tilde # tilde (~) will subscript next char
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - attr_list
  - md_in_html
theme:
  name: material
  variant: classic
  font:
    text: Inter
    code: Fira Code
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tabs # puts major headings in horizontal menu
    - navigation.tabs.sticky # sticky when scrolling down
    - navigation.sections # makes sections NOT collapsed
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide

  palette:
    - primary: blue grey # teal
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # mathjax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # tablesort
  - https://unpkg.com/tablesort@5.6.0/dist/tablesort.min.js
  - javascripts/tablesort.js
