#!/bin/bash
# runproj
# to call the really complicated docker-compose commands from the parent project directory.
echo "running runproj script to run docker-compose. Usage: ./runproj <up [dev|test|prod] | down [dev|test|prod] | exec | root | postgres | pgadmin>"
ACTION="$1"
DEPLOYMENT_ENV=$2
# 2nd parameter if present is the DEPLOYMENT_ENV parameter
if [ -z "$2" ]; then
    # assume it is dev if not specified
    DEPLOYMENT_ENV=dev
fi
# Check if DEPLOYMENT_ENV is in the allowed array
ALLOWED=("dev" "test" "prod")
if [[ " ${ALLOWED[*]} " == *" $DEPLOYMENT_ENV "* ]]; then
    echo "ACTION = ${ACTION}; DEPLOYMENT_ENV=${DEPLOYMENT_ENV}"
else
    echo "Error: Invalid DEPLOYMENT_ENV parameter. Must be blank or in: [${ALLOWED[*]}]"
    exit 1
fi

# pick up the required env vars
source ./docker/.env
source ./docker/${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret

function exec_in {
    # exec into the first container that matches this image (the sed command restricts to 2nd line)
   
    # if called as `exec_in root` then it will enter as root user
    ROOTPARMS=""
    if [[ $1 == "root" ]]; then
        ROOTPARMS=" -u root -w /home/${DEPLOYMENT_ENV}user/$PROJECT_DIR "
    fi
   
    container_name="${DOCKER_PREFIX}_django_${DEPLOYMENT_ENV}"
    CONTAINER=$(docker ps -qf "name=${container_name}")
    echo "container_name = ${container_name}; CONTAINER = ${CONTAINER}"
    docker exec $ROOTPARMS -it $CONTAINER /bin/bash
}

# setup allowed containers for exec
ALLOWED_EXEC=("postgres" "q2" "vite" "redis" "pgadmin")
ALPINE_CONTAINERS=("redis")

if [[ ${ACTION} == "up" ]]
then
    DEPLOYMENT_ENV=${DEPLOYMENT_ENV} \
    COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
    docker compose -f ./docker/docker-compose.yml \
        --env-file ./docker/.env \
        up --detach --build
    echo "open django project after running ./src/manage.py runserver 0:8000"
    # docker exec in
    exec_in
elif [[ $ACTION == "down" ]];
then
    DEPLOYMENT_ENV=${DEPLOYMENT_ENV} \
    COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
    docker compose -f ./docker/docker-compose.yml \
        --env-file ./docker/.env \
        down
elif [[ $ACTION == "exec" ]];
then
    exec_in
elif [[ $ACTION == "root" ]];
then
    exec_in root
elif [[ " ${ALLOWED_EXEC[*]} " == *" $ACTION "* ]];
then
    container_name="${DOCKER_PREFIX}_${ACTION}_${DEPLOYMENT_ENV}"
    CONTAINER=$(docker ps -qf "name=${container_name}")
    echo "container_name = ${container_name}; CONTAINER = ${CONTAINER}"

    if [[ $ACTION == "redis" ]]; then
        SHELL="redis-cli -a $REDIS_PASSWORD"
    elif [[ " ${ALPINE_CONTAINERS[*]} " == *" $ACTION "* ]]; then
        # alpine containers use sh instead of bash
        SHELL="/bin/sh"
    else
        SHELL="/bin/bash"
    fi

    # enter the container
    docker exec -it $CONTAINER $SHELL
else
    echo "You must have only 1 parameter from ['up', 'down', 'exec', 'root', ${${ALLOWED_EXEC[*]}} ]"
    echo "last two in case you need to re-enter the relevant container service]"
fi