# Generated by Django 5.1.7 on 2025-04-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "The Author Person",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("published_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "isbn_empty",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(isbn="", then=True),
                            models.When(isbn__isnull=True, then=True),
                            default=False,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("pages", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "uneditable_field",
                    models.CharField(
                        blank=True, editable=False, max_length=200, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="sample.author",
                    ),
                ),
            ],
        ),
    ]
