# Generated by Django 5.1.7 on 2025-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="an_integer_with_long_heading_text",
            field=models.IntegerField(default=0),
        ),
    ]
