# Generated by Django 5.1.3 on 2024-12-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="uneditable_field",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True
            ),
        ),
    ]
