# Generated by Django 5.1.7 on 2025-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0002_author_an_integer_with_long_heading_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(related_name="books", to="sample.genre"),
        ),
    ]
