# Generated by Django 5.1.5 on 2025-02-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0002_book_uneditable_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn_empty",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(isbn="", then=True),
                    models.When(isbn__isnull=True, then=True),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
