# Generated by Django 5.2 on 2025-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0003_genre_book_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="bestseller",
            field=models.BooleanField(default=False),
        ),
    ]
