# Generated by Django 5.1.9 on 2025-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0004_book_bestseller"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="numeric_string",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="book",
            name="bestseller",
            field=models.BooleanField(
                default=False, help_text="Is this book a bestseller?"
            ),
        ),
    ]
