# Generated by Django 5.2 on 2025-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_genre_numeric_string_alter_book_bestseller'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_title_author'),
        ),
    ]
