# Generated by Django 5.2.4 on 2025-07-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn_empty',
        ),
    ]
