nav:
  - Configuration Options: config_options.md
  - PowerField Reference: powerfields.md
  - PowerAction and PowerButton Reference: poweractions.md
  - Hooks: hooks.md
  - Complete Example: complete_example.md
  - Management Commands: mgmt_commands.md
  - Sample App: sample_app.md
  - Async Architecture: async.md
  - Dockerised Development: dockerised_dev.md
  - Testing: testing.md
  - Renovate: renovate.md
  - Deprecations: deprecations.md
