# Generated by Django 5.2.5 on 2025-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_asynctaskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctaskrecord",
            name="task_name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="asynctaskrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
