# Generated by Django 5.2.4 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0005_author_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="priority_band",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Review", "Review"),
                    ("Paused", "Paused"),
                ],
                default="Active",
                max_length=16,
            ),
        ),
    ]
