name: powercrud-${DEPLOYMENT_ENV}

services:

  pgadmin:
    container_name: ${DOCKER_PREFIX}_pgadmin_${DEPLOYMENT_ENV}
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5051:80"
    volumes:
      - powercrud-pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret

  powercrud_postgres:
    image: postgres:16
    container_name: ${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
    restart: always
    environment:
      - POSTGRES_DB=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Testing123
    ports:
      - 5433:5433 # avoid clash with normal postgres port
    volumes:
      - ${DOCKER_PREFIX}_pgdata:/var/lib/postgresql/data
      # mount the config file
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    command: postgres

  powercrud_django:
    image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
    container_name: ${DOCKER_PREFIX}_django_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    build:
      dockerfile: docker/dockerfile_django
      context: "${PWD}"
      args:
        PROJECT_DIR: $PROJECT_DIR
        HOST_POETRY_FILES: .
        DOCKER_DIRECTORY: docker
        USER: ${DEPLOYMENT_ENV}user
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
      env: DISPLAY
      DJANGO_LIFECYCLE_ENV: ${DEPLOYMENT_ENV}
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_PROJECT_NAME: ${PROJECT_DIR}
      DATABASE_NAME: ${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      DATABASE_HOST: ${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: True
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 8001:8001
      - 10005:10005  # for mkdocs serve
    depends_on:
      - powercrud_postgres
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"
      - "/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}/node_modules"
      - "${HOME}/.ssh:/home/${DEPLOYMENT_ENV}user/.ssh"
      - "${HOME}/.gitconfig:/home/${DEPLOYMENT_ENV}user/.gitconfig"

  powercrud_vite:
    image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
    container_name: ${DOCKER_PREFIX}_vite_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
      DJANGO_LIFECYCLE_ENV: ${DEPLOYMENT_ENV}
      DJANGO_SETTINGS_MODULE: config.settings
    working_dir: /home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}/src
    ports:
      - 5174:5174
    volumes:
      - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"
      - "/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}/node_modules"
    user: ${DEPLOYMENT_ENV}user
    command: npm run dev -- --host 0.0.0.0

  redis:
    container_name: ${DOCKER_PREFIX}_redis_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - powercrud_redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  powercrud-pgadmin-data:
    name: ${DOCKER_PREFIX}_pgadmin_data
  powercrud_redis_data:
    name: ${DOCKER_PREFIX}_redis_data
  powercrud_pgdata:
    driver: local
    name: ${DOCKER_PREFIX}_pgdata

