services:

  pgadmin:
    container_name: django_nominopolitan_pgadmin_${DEPLOYMENT_ENV}
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret

  django_nominopolitan_postgres:
    image: postgres:16
    container_name: django_nominopolitan_postgres_${DEPLOYMENT_ENV}
    restart: always
    environment:
      - POSTGRES_DB=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Testing123
    ports:
      - 5432:5432
    volumes:
      - django_nominopolitan_pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'

  django_nominopolitan_django:
    image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
    container_name: ${DOCKER_PREFIX}_django_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    build:
      dockerfile: docker/dockerfile_django
      context: "${PWD}"
      args:
        PROJECT_DIR: $PROJECT_DIR
        HOST_POETRY_FILES: .
        DOCKER_DIRECTORY: docker
        USER: ${DEPLOYMENT_ENV}user
        # Remove API credentials - not needed for nominopolitan
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
      env: DISPLAY
      DJANGO_LIFECYCLE_ENV: ${DEPLOYMENT_ENV}
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_PROJECT_NAME: ${PROJECT_DIR}
      DATABASE_NAME: ${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      DATABASE_HOST: ${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: True
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 8001:8001
      - 10005:10005  # for mkdocs serve
    depends_on:
      - django_nominopolitan_postgres
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"
      - "/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}/node_modules"
      - "${HOME}/.ssh:/home/${DEPLOYMENT_ENV}user/.ssh"
      - "${HOME}/.gitconfig:/home/${DEPLOYMENT_ENV}user/.gitconfig"

  django_nominopolitan_vite:
    image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
    container_name: ${DOCKER_PREFIX}_vite_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    environment:
      PROJECT_DIR: ${PROJECT_DIR}
      DJANGO_LIFECYCLE_ENV: ${DEPLOYMENT_ENV}
      DJANGO_SETTINGS_MODULE: config.settings
    working_dir: /home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}
    ports:
      - 5174:5174
    volumes:
      - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"
      - "/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}/node_modules"
    user: ${DEPLOYMENT_ENV}user
    command: npm run dev -- --host 0.0.0.0

  redis:
    container_name: ${DOCKER_PREFIX}_redis_${DEPLOYMENT_ENV}
    env_file:
      - ./${DEPLOYMENT_ENV}/${DEPLOYMENT_ENV}.secret
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "60", "1", "--loglevel", "warning"]

  # COMMENTED OUT - Can add back later if needed
  # celery_worker:
  #   image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
  #   container_name: ${DOCKER_PREFIX}_celery_worker_${DEPLOYMENT_ENV}
  #   depends_on:
  #     - redis
  #     - django_nominopolitan_postgres
  #   environment:
  #     - DJANGO_LIFECYCLE_ENV=${DEPLOYMENT_ENV}
  #     - DJANGO_SETTINGS_MODULE=django_nominopolitan.settings
  #     - DJANGO_PROJECT_NAME=${PROJECT_DIR}
  #     - DATABASE_NAME=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
  #     - DATABASE_HOST=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
  #     - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   working_dir: /home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}
  #   command: celery -A django_nominopolitan worker -l INFO
  #   volumes:
  #     - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"
  #     - "${HOME}/.ssh:/home/${DEPLOYMENT_ENV}user/.ssh"
  #     - "${HOME}/.gitconfig:/home/${DEPLOYMENT_ENV}user/.gitconfig"

  # celery_beat:
  #   image: ${DOCKER_PREFIX}_django:${DEPLOYMENT_ENV}
  #   container_name: ${DOCKER_PREFIX}_celery_beat_${DEPLOYMENT_ENV}
  #   depends_on:
  #     - redis
  #     - django_nominopolitan_postgres
  #   environment:
  #     - DJANGO_LIFECYCLE_ENV=${DEPLOYMENT_ENV}
  #     - DJANGO_SETTINGS_MODULE=django_nominopolitan.settings
  #     - DJANGO_PROJECT_NAME=${PROJECT_DIR}
  #     - DATABASE_NAME=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
  #     - DATABASE_HOST=${DOCKER_PREFIX}_postgres_${DEPLOYMENT_ENV}
  #     - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   working_dir: /home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}
  #   command: celery -A django_nominopolitan beat -l INFO
  #   volumes:
  #     - "${PWD}:/home/${DEPLOYMENT_ENV}user/${PROJECT_DIR}"

volumes:
  pgadmin-data:
    name: django_nominopolitan_pgadmin_data
  redis_data:
    name: django_nominopolitan_redis_data
  django_nominopolitan_pgdata:
    driver: local
    name: django_nominopolitan_pgdata

